#include "instruction-sequence.inc"

// souffle --verbose -D./output -F./input/ -I./datalog-logic ./ssa-query.dl

//////////
// QUERY
//////////

.init InstSeq = InstructionSequence
.input InstSeq.var_def
.input InstSeq.successor
.input InstSeq.entry_instruction

.decl imdom(n:Instruction,s:Instruction)
.output imdom()
imdom(n,s) :- InstSeq.imdom(n,s).

.decl phi_location(v : Variable , m : Instruction)
.output phi_location()
phi_location(v, i) :- InstSeq.phi_location(v, i).
